#!/usr/bin/env bash
# 手動補傳貼紙：想起來就打 `stik`。可隨時 Ctrl-C，下次接著跑（已傳的自動跳過）。
# 全自動：補傳 → 同步房間貼紙包(新舊 MSC 都發) → 自動 commit+push → GitHub Pages 自動部署。
# 提交訊息全自動產生，你不用想任何文字。中途 Ctrl-C 或斷網也會先把已下載的推上去。
set -uo pipefail
cd /home/avatar/Downloads/stickerpicker || { echo "找不到 stickerpicker 目錄"; exit 1; }

# ── 自動提交＋推送（訊息自動產生，無需人工組織語言）──────────────────
deploy() {
  git add web/packs >/dev/null 2>&1
  if git diff --cached --quiet -- web/packs 2>/dev/null; then
    echo "   web/packs 無新變更,不需部署"
    return 0
  fi
  local n added
  n=$(ls web/packs/*.json 2>/dev/null | wc -l)
  added=$(git diff --cached --name-only --diff-filter=A -- web/packs 2>/dev/null | wc -l)
  git commit -q -m "stickers: sync web picker ($n packs, +$added new)" \
    -m "Auto-generated by scripts/resume_stickers.sh on $(date '+%F %T %Z')." 2>/dev/null
  if GIT_SSH_COMMAND='ssh -o BatchMode=yes -o ConnectTimeout=20' \
       git push --verbose -q origin master 2>/dev/null; then
    echo "   ✅ 已推送 ($n 包, 新增 $added) → GitHub Pages 約 1-3 分鐘自動部署"
  else
    echo "   ⚠ 推送失敗(網路?)。已在本機提交好,下次跑 stik 會自動重推。"
  fi
}
# Ctrl-C / 中斷 / 正常結束都先把已下載的部署掉，絕不白費
on_exit() { echo ""; echo "▶ 收尾：部署已下載的包…"; deploy; }
trap on_exit EXIT

# ── 全部補完？只確保房間+Pages 最新 ─────────────────────────────────
if .venv/bin/python scripts/holes.py >/dev/null 2>&1; then
  echo "✅ Telegram 的貼紙已全部補齊。同步房間確保最新…"
  .venv/bin/python scripts/msc2545_room_sync.py --force
  exit 0
fi

HS=$(python3 -c "import json;print(json.load(open('config.json'))['homeserver'].rstrip('/'))")
TOK=$(python3 -c "import json;print(json.load(open('config.json'))['access_token'])")

# ── 配額閘 ──────────────────────────────────────────────────────────
PROBE=$(mktemp); head -c 200000 /dev/urandom > "$PROBE"
CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 -X POST \
  "$HS/_matrix/media/v3/upload?filename=probe.bin" \
  -H "Authorization: Bearer $TOK" -H "Content-Type: application/octet-stream" \
  --data-binary @"$PROBE")
command rm -f "$PROBE"

if [ "$CODE" = "401" ] || { [ "$CODE" = "403" ] && curl -s --max-time 20 \
     "$HS/_matrix/client/v3/account/whoami" -H "Authorization: Bearer $TOK" \
     | grep -q M_UNKNOWN_TOKEN; }; then
  echo "⚠ Matrix token 失效了（HTTP $CODE）。到 config.json 換上新的 access_token 再跑。"
  exit 1
fi
if [ "$CODE" != "200" ]; then
  echo "⏳ Matrix 媒體配額還沒回（HTTP $CODE）。過陣子想起來再跑一次 stik。"
  echo "   進度：$(ls web/packs/*.json 2>/dev/null | wc -l) 包已下載"
  .venv/bin/python scripts/holes.py 2>/dev/null | head -1
  exit 0
fi

# ── 補傳 ────────────────────────────────────────────────────────────
echo "▶ 配額 OK，開始補傳（可隨時 Ctrl-C，已下載的會自動部署）…"
STICKER_UPLOAD_ATTEMPTS=5 STICKER_JOBS=6 STICKER_PACK_JOBS=2 \
  .venv/bin/sticker-import --list 2>/dev/null \
  | grep -oP '(?<=addstickers/)[A-Za-z0-9_-]+' \
  | xargs -r -n 8 .venv/bin/sticker-import

echo "▶ 同步房間貼紙包（im.ponies + m.room.image_pack 兩種型別）…"
.venv/bin/python scripts/msc2545_room_sync.py --force

echo "—— 目前剩餘 ——"
.venv/bin/python scripts/holes.py 2>/dev/null | head -1
echo "（還有缺就代表配額又滿了；下次想起來再跑 stik）"
